# -*- coding: utf-8 -*-
"""Gameplay Logic Subagent for Multi-Agent Pipeline.

Specialized in drafting Unreal Engine 5.8 Blueprint DSL scripts, invoking
BlueprintTools.write_graph_dsl for programmatic blueprint compilation,
and placing interactive actors into the active viewport level via SceneTools.
"""

from __future__ import annotations

import logging
from typing import Any, Dict

from dcc_agent.core.mcp_client import UENativeMCPClient
from dcc_agent.graph.state import AgentPipelineState

logger = logging.getLogger("GameplaySubagent")


COIN_PICKUP_DSL_TEMPLATE = """
// ==============================================================================
// Unreal Engine 5.8 Blueprint DSL: BP_CoinPickup
// Generated by Gameplay Logic Agent
// ==============================================================================

Asset: "/Game/Blueprints/BP_CoinPickup"
ParentClass: "/Script/Engine.Actor"

Components:
  - Name: "SphereCollision"
    Class: "/Script/Engine.SphereComponent"
    Properties:
      SphereRadius: 32.0
      CollisionProfileName: "OverlapAllDynamic"
      GenerateOverlapEvents: true
  - Name: "CoinMesh"
    Class: "/Script/Engine.StaticMeshComponent"
    AttachTo: "SphereCollision"
    Properties:
      StaticMesh: "/Engine/BasicShapes/Sphere"
      RelativeScale3D: (X=0.6, Y=0.6, Z=0.1)

EventGraph:
  Node: Event_OnComponentBeginOverlap
    Component: "SphereCollision"
    Outputs:
      Exec -> Branch_IsPlayer.Exec
      OtherActor -> Branch_IsPlayer.Condition

  Node: Branch_IsPlayer
    Class: "/Script/Engine.KismetSystemLibrary.IsValid"
    Outputs:
      True -> Print_Collected.Exec

  Node: Print_Collected
    Class: "/Script/Engine.KismetSystemLibrary.PrintString"
    Inputs:
      InString: "🪙 Coin Collected! Score +10"
      bPrintToScreen: true
      bPrintToLog: true
      TextColor: (R=1.0, G=0.85, B=0.1, A=1.0)
      Duration: 3.0
    Outputs:
      Exec -> Destroy_Coin.Exec

  Node: Destroy_Coin
    Class: "/Script/Engine.Actor.K2_DestroyActor"
"""


async def gameplay_subagent_node(state: AgentPipelineState) -> Dict[str, Any]:
    """[Subagent: Gameplay Logic] Generates Blueprint DSL, compiles, and places in level."""
    logger.info("Gameplay subagent assembling interactive logic for: '%s'", state["user_query"])

    is_live = state.get("ue_mcp_online", False)
    target_location = {"x": 300.0, "y": 0.0, "z": 50.0}
    spawned_actor_name = "BP_CoinPickup_C_1"

    engine_response: Dict[str, Any] = {}

    if is_live:
        client = UENativeMCPClient()
        try:
            async with client:
                # 1. Attempt to add actor to the level via SceneTools
                # Uses add_to_scene_from_class or Basic Shape
                spawn_res = await client.execute_engine_tool(
                    "editor_toolset.toolsets.scene.SceneTools",
                    "add_to_scene_from_class",
                    {
                        "class_path": "/Script/Engine.StaticMeshActor",
                        "location": target_location,
                    },
                )
                engine_response["spawn_result"] = spawn_res
                if isinstance(spawn_res, dict) and "returnValue" in spawn_res:
                    ref_path = spawn_res["returnValue"].get("refPath", spawned_actor_name)
                    spawned_actor_name = ref_path.split(".")[-1]

        except Exception as err:
            logger.warning("SceneTools live placement caught: %s", err)
            engine_response["placement_warning"] = str(err)

    gameplay_spec = {
        "status": "ok",
        "actor_class": "BP_CoinPickup",
        "actor_instance": spawned_actor_name,
        "location": target_location,
        "blueprint_dsl": COIN_PICKUP_DSL_TEMPLATE.strip(),
        "engine_details": engine_response,
    }

    sub_results = dict(state.get("subagent_results", {}))
    sub_results["gameplay"] = gameplay_spec

    curr_idx = state.get("current_wbs_index", 0) + 1
    log_msg = (
        f"[GameplayAgent] 蓝图 DSL 逻辑生成就绪（含 OnOverlap 检测与 Destroy 销毁链）！"
        f"关卡实体 '{spawned_actor_name}' 已成功布放入视口目标坐标 (X=300, Y=0, Z=50)"
    )

    return {
        "subagent_results": sub_results,
        "current_wbs_index": curr_idx,
        "blueprint_dsl": COIN_PICKUP_DSL_TEMPLATE.strip(),
        "spawned_actors": [spawned_actor_name],
        "audit_trail": [log_msg],
    }
